name = "z-and-l-logistics-monitor"
compatibility_date = "2026-05-03"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "z-and-l-logistics"
database_id = "2f5696b0-b87b-410b-be5b-05ab34ae3f14"
migrations_dir = "migrations"
